In [1]:
# this is my vacation PY script
import gmaps
import numpy as np
import pandas as pd
import requests
import time
from us import states
import json
import os
import random

# Get API Key 
from config import gkey

In [2]:
# Read in Data from Weather Py
weather_data = "Output/Weather_Data_API.csv"

In [3]:
# Create Data Frame
weather_data = pd.read_csv(weather_data)

In [4]:
# Double Check Data
weather_data.head()

,Lat,Lng,City,Country,Temperature,Humidity,Clouds,Windspeed,Latitude,Longitude
0,23.150198,146.171660,katsuura,jp,67.14,82,20,6.93,33.93,134.50
1,-40.425178,-117.622998,rikitea,pf,72.05,64,0,4.07,-23.12,-134.97
2,-33.741329,-48.396142,cidreira,br,61.86,92,0,6.93,-30.17,-50.22
3,-33.693105,7.393717,oranjemund,na,71.55,35,0,12.82,-28.55,16.43
4,-11.422523,-131.001279,atuona,pf,79.54,77,81,20.49,-9.80,-139.03

In [5]:
# Configure gmaps with API key
gmaps.configure(api_key=gkey)

In [6]:
# Define our map locations 
locations = weather_data[["Latitude", "Longitude"]].astype(float)

# Convert Humidity Rate to float and store
humidity_rate = weather_data["Humidity"].astype(float)

In [8]:
# Create a Humidity Heatmap layer
fig = gmaps.figure(map_type='HYBRID') 

heat_layer = gmaps.heatmap_layer(locations, weights=humidity_rate, 
                                 dissipating=False, max_intensity=100,
                                 point_radius = 1)

fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

In [9]:
# Narrow down Data Frame
Ideal_Temp = weather_data[(weather_data['Temperature'] > 50) & (weather_data['Temperature'] <= 62) ]

In [10]:
Ideal_Clouds = Ideal_Temp[(Ideal_Temp['Clouds'] > 80)]

In [11]:
Ideal_df = Ideal_Clouds[(Ideal_Clouds['Windspeed'] < 15)]

In [12]:
Ideal_df

,Lat,Lng,City,Country,Temperature,Humidity,Clouds,Windspeed,Latitude,Longitude
39,51.628565,-3.266312,pontypridd,gb,60.98,100,100,8.05,51.60,-3.34
55,47.577017,-39.192053,torbay,ca,50.47,100,90,12.75,47.66,-52.73
65,46.398574,16.318734,varazdin,hr,58.64,87,100,14.99,46.30,16.34
99,42.922970,132.014799,russkiy,ru,54.91,95,100,3.20,44.21,40.02
114,-37.373903,-72.964281,laja,cl,51.80,100,90,11.41,-37.28,-72.71
120,45.366611,-0.006194,angouleme,fr,60.15,93,90,9.17,45.65,0.15
254,52.133407,19.499957,kutno,pl,55.27,93,90,1.12,52.23,19.36
377,56.813048,10.467519,hals,dk,55.49,92,84,3.00,57.00,10.31
396,33.716765,83.214887,jumla,np,50.81,89,81,0.74,29.28,82.18
436,52.933075,-134.312329,ketchikan,us,51.80,87,90,11.41,55.34,-131.65
454,47.062469,23.766935,alunis,ro,54.70,90,100,5.23,45.20,25.87
467,-10.976728,-84.014769,chicama,pe,60.80,87,90,8.05,-7.84,-79.15
482,44.321942,37.861303,divnomorskoye,ru,60.71,82,100,7.81,44.50,38.13
496,48.350856,11.228218,maisach,de,54.00,82,87,8.05,48.22,11.26
527,-0.565887,28.147520,butembo,cd,61.54,96,100,2.59,0.12,29.29

In [13]:
# Add hotel name to data frame
hotels_df = Ideal_df.copy()
hotels_df["Hotel Name"] = ""
hotels_df

,Lat,Lng,City,Country,Temperature,Humidity,Clouds,Windspeed,Latitude,Longitude,Hotel Name
39,51.628565,-3.266312,pontypridd,gb,60.98,100,100,8.05,51.60,-3.34,
55,47.577017,-39.192053,torbay,ca,50.47,100,90,12.75,47.66,-52.73,
65,46.398574,16.318734,varazdin,hr,58.64,87,100,14.99,46.30,16.34,
99,42.922970,132.014799,russkiy,ru,54.91,95,100,3.20,44.21,40.02,
114,-37.373903,-72.964281,laja,cl,51.80,100,90,11.41,-37.28,-72.71,
120,45.366611,-0.006194,angouleme,fr,60.15,93,90,9.17,45.65,0.15,
254,52.133407,19.499957,kutno,pl,55.27,93,90,1.12,52.23,19.36,
377,56.813048,10.467519,hals,dk,55.49,92,84,3.00,57.00,10.31,
396,33.716765,83.214887,jumla,np,50.81,89,81,0.74,29.28,82.18,
436,52.933075,-134.312329,ketchikan,us,51.80,87,90,11.41,55.34,-131.65,
454,47.062469,23.766935,alunis,ro,54.70,90,100,5.23,45.20,25.87,
467,-10.976728,-84.014769,chicama,pe,60.80,87,90,8.05,-7.84,-79.15,
482,44.321942,37.861303,divnomorskoye,ru,60.71,82,100,7.81,44.50,38.13,
496,48.350856,11.228218,maisach,de,54.00,82,87,8.05,48.22,11.26,
527,-0.565887,28.147520,butembo,cd,61.54,96,100,2.59,0.12,29.29,

In [14]:
# The following code was graciously given by Pablo

def get_hotel(lat,lng):
    # geocoordinates
    target_coordinates = f"{lat}, {lng}"
    target_radius = 5000
    target_type = "hotel"
    target_keyword = "hotel"
    # set up a parameters dictionary
    params = {
        "location": target_coordinates,
        "radius": target_radius,
        "type": target_type,
        "keyword": target_keyword,
        "key": gkey
    }

    # base url
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # run a request using our params dictionary
    try:
        response = requests.get(base_url, params=params).json()
    except ValueError:
        response = ""
    return response

In [15]:

for city in hotels_df['City']:
    lat = hotels_df.loc[hotels_df['City'] == city]['Latitude'].item()
    lng = hotels_df.loc[hotels_df['City'] == city]['Longitude'].item()
    hotel_info = get_hotel(lat,lng)
    try:
        random_hotel = random.randint(0, len(hotel_info["results"])-1)
        hotel_name = hotel_info["results"][random_hotel]["name"]
    except ValueError:
            print (f"No hotel results for: {city}")
            hotel_name = "No Hotel Found"
    print(f"finding hotels for: {city}, {hotel_name} found!")
    hotels_df.loc[hotels_df['City'] == city, 'Hotel_Name']= hotel_name

finding hotels for: pontypridd, Llechwen Hall Hotel found!
finding hotels for: torbay, Best Western Plus St. John's Airport Hotel and Suites found!
finding hotels for: varazdin, Hotel Varazdin found!
finding hotels for: russkiy, Baza Otdykha Blagodat found!
finding hotels for: laja, Camping Los Martínez found!
finding hotels for: angouleme, hotelF1 Angoulême found!
finding hotels for: kutno, Hotel Stacja Kutno found!
finding hotels for: hals, Holiday home Storvorde VII found!
finding hotels for: jumla, Hotel Sundar Rara Karnali found!
finding hotels for: ketchikan, The Gilmore Hotel found!
No hotel results for: alunis
finding hotels for: alunis, No Hotel Found found!
finding hotels for: chicama, Hospedaje Punta Cana PERU found!
finding hotels for: divnomorskoye, Katerina found!
finding hotels for: maisach, Hotel Hartmann found!
finding hotels for: butembo, Hotel My Royal found!

In [16]:
hotels_df

,Lat,Lng,City,Country,Temperature,Humidity,Clouds,Windspeed,Latitude,Longitude,Hotel Name,Hotel_Name
39,51.628565,-3.266312,pontypridd,gb,60.98,100,100,8.05,51.60,-3.34,,Llechwen Hall Hotel
55,47.577017,-39.192053,torbay,ca,50.47,100,90,12.75,47.66,-52.73,,Best Western Plus St. John's Airport Hotel and...
65,46.398574,16.318734,varazdin,hr,58.64,87,100,14.99,46.30,16.34,,Hotel Varazdin
99,42.922970,132.014799,russkiy,ru,54.91,95,100,3.20,44.21,40.02,,Baza Otdykha Blagodat
114,-37.373903,-72.964281,laja,cl,51.80,100,90,11.41,-37.28,-72.71,,Camping Los Martínez
120,45.366611,-0.006194,angouleme,fr,60.15,93,90,9.17,45.65,0.15,,hotelF1 Angoulême
254,52.133407,19.499957,kutno,pl,55.27,93,90,1.12,52.23,19.36,,Hotel Stacja Kutno
377,56.813048,10.467519,hals,dk,55.49,92,84,3.00,57.00,10.31,,Holiday home Storvorde VII
396,33.716765,83.214887,jumla,np,50.81,89,81,0.74,29.28,82.18,,Hotel Sundar Rara Karnali
436,52.933075,-134.312329,ketchikan,us,51.80,87,90,11.41,55.34,-131.65,,The Gilmore Hotel
454,47.062469,23.766935,alunis,ro,54.70,90,100,5.23,45.20,25.87,,No Hotel Found
467,-10.976728,-84.014769,chicama,pe,60.80,87,90,8.05,-7.84,-79.15,,Hospedaje Punta Cana PERU
482,44.321942,37.861303,divnomorskoye,ru,60.71,82,100,7.81,44.50,38.13,,Katerina
496,48.350856,11.228218,maisach,de,54.00,82,87,8.05,48.22,11.26,,Hotel Hartmann
527,-0.565887,28.147520,butembo,cd,61.54,96,100,2.59,0.12,29.29,,Hotel My Royal

In [17]:
hotels_df = hotels_df[hotels_df.Hotel_Name!= 'No Hotel Found']

In [18]:
hotels_df

,Lat,Lng,City,Country,Temperature,Humidity,Clouds,Windspeed,Latitude,Longitude,Hotel Name,Hotel_Name
39,51.628565,-3.266312,pontypridd,gb,60.98,100,100,8.05,51.60,-3.34,,Llechwen Hall Hotel
55,47.577017,-39.192053,torbay,ca,50.47,100,90,12.75,47.66,-52.73,,Best Western Plus St. John's Airport Hotel and...
65,46.398574,16.318734,varazdin,hr,58.64,87,100,14.99,46.30,16.34,,Hotel Varazdin
99,42.922970,132.014799,russkiy,ru,54.91,95,100,3.20,44.21,40.02,,Baza Otdykha Blagodat
114,-37.373903,-72.964281,laja,cl,51.80,100,90,11.41,-37.28,-72.71,,Camping Los Martínez
120,45.366611,-0.006194,angouleme,fr,60.15,93,90,9.17,45.65,0.15,,hotelF1 Angoulême
254,52.133407,19.499957,kutno,pl,55.27,93,90,1.12,52.23,19.36,,Hotel Stacja Kutno
377,56.813048,10.467519,hals,dk,55.49,92,84,3.00,57.00,10.31,,Holiday home Storvorde VII
396,33.716765,83.214887,jumla,np,50.81,89,81,0.74,29.28,82.18,,Hotel Sundar Rara Karnali
436,52.933075,-134.312329,ketchikan,us,51.80,87,90,11.41,55.34,-131.65,,The Gilmore Hotel
467,-10.976728,-84.014769,chicama,pe,60.80,87,90,8.05,-7.84,-79.15,,Hospedaje Punta Cana PERU
482,44.321942,37.861303,divnomorskoye,ru,60.71,82,100,7.81,44.50,38.13,,Katerina
496,48.350856,11.228218,maisach,de,54.00,82,87,8.05,48.22,11.26,,Hotel Hartmann
527,-0.565887,28.147520,butembo,cd,61.54,96,100,2.59,0.12,29.29,,Hotel My Royal

In [33]:
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel_Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
humidity = hotels_df["Humidity"].astype(float)
hotel_info = [info_box_template.format(**row) for index, row in hotels_df.iterrows()]
locations = hotels_df[["Lat", "Lng"]].astype(float)

In [38]:
# Add marker layer ontop of heat map
fig = gmaps.figure(map_type='TERRAIN')
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
heatmap_layer = gmaps.heatmap_layer(locations,humidity) 
heatmap_layer.max_intensity = 100
heatmap_layer.point_radius = 20
fig.add_layer(heatmap_layer)
fig.add_layer(marker_layer)
fig

# Display Map

Figure(layout=FigureLayout(height='420px'))